import type { Claim } from '@/pages/HomePage';
export const MOCK_CLAIMS: Claim[] = [
  {
    id: 'CLM-2024-001',
    policyHolder: 'Sarah Johnson',
    claimType: 'Water Damage',
    status: 'In Progress',
    stage: 'Assessment',
    priority: 'High',
    createdDate: '2024-01-15',
    lastUpdated: '2024-01-20',
    assignedOfficer: 'Michael Chen',
  },
  {
    id: 'CLM-2024-002',
    policyHolder: 'Robert Williams',
    claimType: 'Fire Damage',
    status: 'Pending Review',
    stage: 'Investigation',
    priority: 'Critical',
    createdDate: '2024-01-14',
    lastUpdated: '2024-01-19',
    assignedOfficer: 'Emily Davis',
  },
  {
    id: 'CLM-2024-003',
    policyHolder: 'Jennifer Martinez',
    claimType: 'Theft',
    status: 'Open',
    stage: 'Initial Review',
    priority: 'Medium',
    createdDate: '2024-01-18',
    lastUpdated: '2024-01-18',
    assignedOfficer: 'James Wilson',
  },
  {
    id: 'CLM-2024-004',
    policyHolder: 'David Brown',
    claimType: 'Wind Damage',
    status: 'Approved',
    stage: 'Payment Processing',
    priority: 'Medium',
    createdDate: '2024-01-10',
    lastUpdated: '2024-01-17',
    assignedOfficer: 'Michael Chen',
  },
  {
    id: 'CLM-2024-005',
    policyHolder: 'Lisa Anderson',
    claimType: 'Hail Damage',
    status: 'In Progress',
    stage: 'Assessment',
    priority: 'High',
    createdDate: '2024-01-12',
    lastUpdated: '2024-01-19',
    assignedOfficer: 'Emily Davis',
  },
  {
    id: 'CLM-2024-006',
    policyHolder: 'Thomas Garcia',
    claimType: 'Vandalism',
    status: 'Open',
    stage: 'Initial Review',
    priority: 'Low',
    createdDate: '2024-01-19',
    lastUpdated: '2024-01-19',
    assignedOfficer: 'James Wilson',
  },
  {
    id: 'CLM-2024-007',
    policyHolder: 'Patricia Taylor',
    claimType: 'Water Damage',
    status: 'Rejected',
    stage: 'Closed',
    priority: 'Low',
    createdDate: '2024-01-08',
    lastUpdated: '2024-01-16',
    assignedOfficer: 'Michael Chen',
  },
  {
    id: 'CLM-2024-008',
    policyHolder: 'Christopher Lee',
    claimType: 'Smoke Damage',
    status: 'In Progress',
    stage: 'Investigation',
    priority: 'High',
    createdDate: '2024-01-13',
    lastUpdated: '2024-01-20',
    assignedOfficer: 'Emily Davis',
  },
  {
    id: 'CLM-2024-009',
    policyHolder: 'Mary Rodriguez',
    claimType: 'Lightning Strike',
    status: 'Pending Review',
    stage: 'Assessment',
    priority: 'Critical',
    createdDate: '2024-01-16',
    lastUpdated: '2024-01-20',
    assignedOfficer: 'James Wilson',
  },
  {
    id: 'CLM-2024-010',
    policyHolder: 'Daniel White',
    claimType: 'Fallen Tree',
    status: 'Approved',
    stage: 'Payment Processing',
    priority: 'Medium',
    createdDate: '2024-01-11',
    lastUpdated: '2024-01-18',
    assignedOfficer: 'Michael Chen',
  },
  {
    id: 'CLM-2024-011',
    policyHolder: 'Karen Harris',
    claimType: 'Water Damage',
    status: 'In Progress',
    stage: 'Investigation',
    priority: 'High',
    createdDate: '2024-01-17',
    lastUpdated: '2024-01-20',
    assignedOfficer: 'Emily Davis',
  },
  {
    id: 'CLM-2024-012',
    policyHolder: 'Steven Clark',
    claimType: 'Roof Damage',
    status: 'Open',
    stage: 'Initial Review',
    priority: 'Medium',
    createdDate: '2024-01-19',
    lastUpdated: '2024-01-19',
    assignedOfficer: 'James Wilson',
  },
];
export const MOCK_CASE_DATA: Record<string, Record<string, string>> = {
  'CLM-2024-001': {
    claimAmount: '$45,000',
    deductible: '$2,500',
    policyNumber: 'HO5-2024-789456',
    incidentDate: '2024-01-10',
    reportedDate: '2024-01-15',
    propertyAddress: '123 Oak Street, Springfield, IL 62701',
    damageType: 'Burst Pipe - Kitchen',
    estimatedRepairCost: '$42,500',
    adjusterNotes: 'Significant water damage to kitchen and adjacent living room. Hardwood floors affected.',
  },
};
export const MOCK_STAGES = [
  { id: '1', name: 'Initial Review', status: 'Completed', completedDate: '2024-01-15' },
  { id: '2', name: 'Assessment', status: 'In Progress', completedDate: null },
  { id: '3', name: 'Investigation', status: 'Pending', completedDate: null },
  { id: '4', name: 'Approval', status: 'Pending', completedDate: null },
  { id: '5', name: 'Payment Processing', status: 'Pending', completedDate: null },
  { id: '6', name: 'Closed', status: 'Pending', completedDate: null },
];
export const MOCK_TASKS = [
  {
    id: 'TSK-001',
    title: 'Review Property Photos',
    status: 'Completed',
    assignee: 'Michael Chen',
    dueDate: '2024-01-16',
    completedDate: '2024-01-16',
  },
  {
    id: 'TSK-002',
    title: 'Schedule On-Site Inspection',
    status: 'In Progress',
    assignee: 'Michael Chen',
    dueDate: '2024-01-22',
    completedDate: null,
  },
  {
    id: 'TSK-003',
    title: 'Verify Policy Coverage',
    status: 'Pending',
    assignee: 'Sarah Thompson',
    dueDate: '2024-01-25',
    completedDate: null,
  },
];
export const MOCK_DOCUMENTS = [
  { id: '1', name: 'Claim Form.pdf', type: 'PDF', size: '2.4 MB', uploadedDate: '2024-01-15', uploadedBy: 'Sarah Johnson' },
  { id: '2', name: 'Property Photos.zip', type: 'ZIP', size: '18.7 MB', uploadedDate: '2024-01-15', uploadedBy: 'Sarah Johnson' },
  { id: '3', name: 'Repair Estimate.pdf', type: 'PDF', size: '1.2 MB', uploadedDate: '2024-01-18', uploadedBy: 'Michael Chen' },
  { id: '4', name: 'Police Report.pdf', type: 'PDF', size: '856 KB', uploadedDate: '2024-01-16', uploadedBy: 'Sarah Johnson' },
];
export const MOCK_AUDIT_EVENTS = [
  { id: '1', timestamp: '2024-01-20 14:32', user: 'Michael Chen', action: 'Updated case status', details: 'Changed status from Open to In Progress' },
  { id: '2', timestamp: '2024-01-19 10:15', user: 'Michael Chen', action: 'Completed task', details: 'Task: Review Property Photos' },
  { id: '3', timestamp: '2024-01-18 16:45', user: 'Michael Chen', action: 'Uploaded document', details: 'Document: Repair Estimate.pdf' },
  { id: '4', timestamp: '2024-01-16 09:20', user: 'Sarah Johnson', action: 'Uploaded document', details: 'Document: Police Report.pdf' },
  { id: '5', timestamp: '2024-01-15 11:30', user: 'System', action: 'Stage completed', details: 'Stage: Initial Review' },
  { id: '6', timestamp: '2024-01-15 08:45', user: 'Sarah Johnson', action: 'Claim submitted', details: 'Initial claim submission' },
];